excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Tests.swift
line_length: 1000
identifier_name:
    min_length: 1
    error: 4
    excluded:
    - id
    - URL

